package com.cloudsheeptech.shoppinglist.data.user

import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.serialization.Contextual
import java.time.OffsetDateTime

/*
* This class is meant to store all relevant data for the local user
* in a room database.
* All fields must be set and cannot be omitted for the storage and
* retrieval actions.
*/

@Entity(tableName = "user")
data class AppUser(
    /* This field is only meant for the use in the local database
    * It should not be exported onto the wire and otherwise ignored by the
    * remote endpoint. */
    @PrimaryKey(autoGenerate = true)
    var ID: Long = 1L,
    /* This ID is meant to identify the user online and process authentication
    * and map lists or other information towards an user. Can only be set once
    * the user successfully logged into the online server, otherwise 0L. */
    var OnlineID : Long = 0L,
    /* The username should identify the application user in a human read-able
    * format. */
    var Username : String,
    /* This field is meant to authenticate the user online against the server
    * and allow for access control. MUST BE GENERATED BY A (PSEUDO)-RANDOM GENERATOR.
    */
    var Password : String,
    /* Set only once during creation. */
    @Contextual
    var Created: OffsetDateTime?,
)
